### PR TITLE
1.17-Support

### PR DESCRIPTION
**Pull request by Jakllp**
Due to some NMS-Changes in 1.17 I had to make changes to the reflection and also the fields being altered.

Basically everything is repackaged and nearly all the fields got renamed and as for the pitch... It's in a different place now

### CODE REVIEW

**Comment by Jakllp** [comment]
Closed due to inconsistencies between paper and spigot

**Comment by storm345** [comment]
Mostly alright, though ucars.version referring to the server version and not the version of the plugin is quite misleading and I would prefer if that was changed!

**Comment by Jakllp** [comment]
Done

**Comment by storm345** [comment]
Hmm looking more closely what you have it totally fine but there would be a more robust way of coding your version check. Eg. if the version changed to 2.0.0 it would currently break. You could instead read the major.minor.minor2 version numbers via a regex and then compare properly eg. if major <= 1 and minor <= 16 then do the pre 1.17 behaviour, else do the new behaviour

**Comment by storm345** [comment]
Sorry for not putting that in the first review, I know it can be a bit annoying having to keep going back and forth

**Pull request merged**
